name = "automodpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9225d37e12a46e5d711db70208ed3c4ecda9efdd6b7b5758bbe081524572c16"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
