name = "automodpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "929f3672eea54b9ba95ae2b19aae4d1179c024b7c2a55bd977568ff37613e1a3"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
