name = "regrowth"
author = "kilobit"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16b8fccbb3effa0bce62bf58b9a50cfc767addde35c5b707ed93a4b4ba712bec"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks"
